FROM dpastoor/pkglock:latest

# start with pkglock and pull additional system dependencies needed
# to install the pkgset

# needed for new version of ggplot2 dependency chain with sf/udunits
RUN apt-get update \
  &&  apt-get install -y libudunits2-dev libgdal-dev libgeos-dev libproj-dev 
